*Input data;
data mel;
infile '~/BIOS680/data/melanoma.dat';
length stage $4;
input ptid age gender fam rtime rstatus
stime sstatus stage monila mumps ppd pha sksd trico;
if upcase(stage) in ('3A', '3B', '3AB') then stages = 3;
else stages = 4;
if gender=-9 then delete;
if gender=1 then gender=0; *set dummy vars (male=0, female=1);
if gender=2 then gender=1;
run;
* check derived variables;
proc freq data=mel nlevels noprint;
table stages*stage / missing;
table stages*sstatus / missing;
table gender*stages*sstatus/missing;
run;
**********************************************************
* 2 dummy var stratification;
data d;
input gender stages;
cards;
0 3
0 4
1 3
1 4
;
run;
title 'Dummy variable stratification';
proc phreg data=mel; *plots(overlay)=survival; *equivalent survival plot functions;
class stages(ref='3');
model stime*sstatus(0) = gender stages / rl ties=exact;
baseline out=base covariates=d survival=s / rowid=stages;
output out=b1 resmart=mart resdev=dev xbeta=linpred dfbeta=dfgender dfstages;*output residuals;
run;
title;
data base;
set base;
Z ='PH gender 0 stages 3'; *reference;
if gender=0 and stages=4 then Z='PH gender 0 stages 4';
if gender=1 and stages=3 then Z='PH gender 1 stages 3';
if gender=1 and stages=4 then Z='PH gender 1 stages 4';
run;
*plot survival functions for each gender*strata combination
for dummy var stratification;
symbol1 c=black v=none i=step1j l=1; *male stage 3;
symbol2 c=blue v=none i=step1j l=3; *male stage 4;
symbol3 c=red v=none i=step1j l=5; *female stage 3;
symbol4 c=green v=none i=step1j l=7; *female stage 4;
title 'Survival curves by gender*stage (Dummy stratification)';
proc gplot data=base;
plot s*stime=Z;
run;
title;
*****************************************************
* 3 Cox model using `true' stratification;
data e;
input stages;
cards;
3
4
;
run;
title 'True stratification';
proc phreg data=mel plots(overlay=row)=survival; *equivalent survival plot functions;
model stime*sstatus(0) = stages / rl ties=exact;
strata gender;
baseline out=c covariates=e survival=s;
output out=b2 resmart=mart resdev=dev xbeta=linpred dfbeta=dfgender; *output residuals;
run;
title;
data c;
set c;
Z ='PH gender 0 stages 3'; *reference;
if gender=0 and stages=4 then Z='PH gender 0 stages 4';
if gender=1 and stages=3 then Z='PH gender 1 stages 3';
if gender=1 and stages=4 then Z='PH gender 1 stages 4';
run;
*plot survival functions for each gender*strata combination
for dummy var stratification;
symbol1 c=black v=none i=step1j l=1; *male stage 3;
symbol2 c=blue v=none i=step1j l=3; *male stage 4;
symbol3 c=red v=none i=step1j l=5; *female stage 3;
symbol4 c=green v=none i=step1j l=7; *female stage 4;
title 'Survival curves by gender*stage (True stratification)';
proc gplot data=c;
plot s*stime=Z;
run;
title;
* 4 Check graphically which stratication is more appropriate for this data set.;
* Plot Cox-snell residuals for dummy stratification;
proc phreg data=mel noprint;
class stages(ref='3');
model stime*sstatus(0) = gender stages / rl ties=exact;
output out=snell1 logsurv=h loglogs=lls / method=emp; *-h is the cox-snell residual;
run;
data snell1;
set snell1;
h = -h;
cons = 1;
run;
proc phreg data = snell1 noprint;
model h*sstatus(0) = cons;
output out = snell1a logsurv = ls /method = emp;
run;
data snell1b;
set snell1a;
haz = - ls;
run;
proc sort data = snell1b;
by h;
run;
title "Cox-snell residual plot (dummy stratification)";
axis1 order = (0 to 3 by .5) minor = none;
axis2 order = (0 to 3 by .5) minor = none label = ( a=90);
symbol1 i = stepjl c= blue;
symbol2 i = join c = red l = 3;
proc gplot data = snell1b;
plot haz*h =1 h*h =2 /overlay haxis=axis1 vaxis= axis2;
label haz = "Estimated Cumulative Hazard Rates";
label h = "Residual";
run;
quit;
title;
*******************************************************************;
* Plot Cox-snell residuals for true stratification;
proc phreg data=mel noprint;
model stime*sstatus(0) = stages / rl ties=exact;
strata gender;
output out=snell2 logsurv=h loglogs=lls / method=emp; *-h is the cox-snell residual;
run;
data snell2;
set snell2;
h = -h;
cons = 1;
run;
proc phreg data = snell2 noprint;
model h*sstatus(0) = cons;
output out = snell2a logsurv = ls /method = emp;
run;
data snell2b;
set snell2a;
haz = - ls;
run;
proc sort data = snell2b;
by h;
run;
title "Cox-snell residual plot (true stratification)";
axis1 order = (0 to 3 by .5) minor = none;
axis2 order = (0 to 3 by .5) minor = none label = ( a=90);
symbol1 i = stepjl c= blue;
symbol2 i = join c = red l = 3;
proc gplot data = snell2b;
plot haz*h =1 h*h =2 /overlay haxis=axis1 vaxis= axis2;
label haz = "Estimated Cumulative Hazard Rates";
label h = "Residual";
run;
quit;
title;
/*
* Plot deviance residuals by XB;
title 'Deviance residuals by XB in dummy var fit';
proc sgplot data=b1;
scatter x=linpred y=dev;
run;
title 'Deviance residuals by XB in true stratafit';
proc sgplot data=b2;
scatter x=linpred y=dev;
run;
* Plot dfbetas by i;
data b1;
set b1;
i = _n_; *iterates rowID;
run;
data b2;
set b2;
i = _n_; *iterates rowID;
run;
title 'DFBETA gender dummy stratification';
proc sgplot data=b1;
scatter y=dfgender x=i;
run;
title 'DFBETA gender true stratification';
proc sgplot data=b2;
scatter y=dfgender x=i;
run;
title 'DFBETA stages dummy stratification';
proc sgplot data=b1;